CREATE DATABASE IF NOT EXISTS glosario_ia CHARACTER SET utf8mb4 COLLATE utf8mb4_spanish_ci;
USE glosario_ia;
CREATE TABLE IF NOT EXISTS glosario (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(150) NOT NULL,
  definicion TEXT NOT NULL,
  imagen VARCHAR(255) NOT NULL
);
INSERT INTO glosario (nombre, definicion, imagen) VALUES
('Aprendizaje Automático (Machine Learning)','Rama de la inteligencia artificial que permite a las computadoras aprender patrones a partir de datos y mejorar su desempeño sin tener que programar explícitamente cada regla. Se utiliza para realizar predicciones, clasificaciones y tomar decisiones basadas en información previa.','imagenes/glosario/concepto1.jpeg'),
('Aprendizaje Profundo (Deep Learning)','Subcampo del aprendizaje automático que utiliza redes neuronales artificiales con múltiples capas para analizar grandes cantidades de datos y aprender representaciones complejas. Es fundamental en aplicaciones como reconocimiento de imágenes, reconocimiento de voz y generación de contenido.','imagenes/glosario/concepto2.jpeg'),
('IA Generativa','Tipo de inteligencia artificial capaz de crear contenido nuevo a partir de patrones aprendidos de grandes cantidades de datos. Puede generar textos, imágenes, audio, video, código y otros contenidos en respuesta a instrucciones o solicitudes del usuario.','imagenes/glosario/concepto3.jpeg'),
('Red Neuronal','Modelo computacional inspirado de manera simplificada en el funcionamiento de las neuronas biológicas. Está formado por nodos o neuronas artificiales organizados en capas, que procesan información y ajustan sus conexiones durante el entrenamiento para reconocer patrones y resolver problemas.','imagenes/glosario/concepto4.jpeg'),
('Modelo de Lenguaje','Sistema de inteligencia artificial diseñado para procesar, analizar y generar lenguaje humano. Aprende relaciones y patrones entre palabras y otros elementos del lenguaje para poder realizar tareas como completar textos, responder preguntas o generar contenido.','imagenes/glosario/concepto5.jpeg'),
('LLM (Large Language Model)','Modelo de lenguaje de gran escala entrenado con enormes cantidades de datos textuales y, dependiendo del sistema, otros tipos de información. Los LLM pueden comprender y generar texto, resumir información, traducir, responder preguntas y realizar diversas tareas lingüísticas.','imagenes/glosario/concepto6.jpeg'),
('Procesamiento del Lenguaje Natural (PLN)','Área de la inteligencia artificial dedicada a permitir que las computadoras comprendan, interpreten, procesen y generen lenguaje humano. Se aplica en traducción automática, asistentes virtuales, análisis de sentimientos, búsqueda de información y chatbots.','imagenes/glosario/concepto7.jpeg'),
('Visión Artificial','Tecnología de inteligencia artificial que permite a las máquinas analizar e interpretar información visual, como imágenes y videos. Puede utilizarse para identificar objetos, detectar características, inspeccionar productos o interpretar escenas.','imagenes/glosario/concepto8.jpeg'),
('Aprendizaje Supervisado','Método de aprendizaje automático en el que el modelo se entrena utilizando datos previamente etiquetados, es decir, ejemplos en los que se conoce la respuesta correcta. A partir de estos ejemplos, aprende a realizar predicciones sobre datos nuevos.','imagenes/glosario/concepto9.jpeg'),
('Aprendizaje No Supervisado','Método de aprendizaje automático que trabaja con datos que no tienen etiquetas o respuestas previamente establecidas. El algoritmo busca por sí mismo patrones, agrupaciones, relaciones o estructuras dentro de los datos.','imagenes/glosario/concepto10.jpeg'),
('Visión por Computadora','Campo de la inteligencia artificial que busca que las computadoras puedan obtener información significativa a partir de imágenes y videos. Permite tareas como reconocimiento de objetos, clasificación de imágenes, detección de rostros y análisis de escenas.','imagenes/glosario/concepto11.jpeg'),
('Chatbot','Programa diseñado para mantener conversaciones con personas mediante lenguaje natural, generalmente a través de texto o voz. Puede responder preguntas, proporcionar información, realizar determinadas tareas y ofrecer asistencia de manera automatizada.','imagenes/glosario/concepto12.png'),
('Gemelos Digitales','Representaciones digitales de objetos, sistemas, procesos o incluso entornos físicos reales. Pueden utilizar datos obtenidos del mundo real para simular, monitorear y analizar el comportamiento del elemento representado, facilitando la detección de problemas y la optimización.','imagenes/glosario/concepto13.jpeg'),
('Aprendizaje por Refuerzo','Método de aprendizaje automático en el que un agente aprende mediante la interacción con un entorno. Recibe recompensas o penalizaciones dependiendo de sus acciones y utiliza esa experiencia para aprender estrategias que le permitan alcanzar determinados objetivos.','imagenes/glosario/concepto14.jpeg'),
('IA Multimodal','Tipo de inteligencia artificial capaz de trabajar con diferentes modalidades de información, como texto, imágenes, audio y video, de manera combinada. Esto permite que un sistema pueda interpretar distintos tipos de información para comprender mejor una solicitud y generar respuestas más completas.','imagenes/glosario/concepto15.jpeg');
